runtime: python27
threadsafe: true
api_version: 1


default_expiration: "10m"

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|json|txt|webmanifest))$
  static_files: dist/AngularAdvisors/\1
  upload: dist/AngularAdvisors/(.*)

- url: /(.*)
  static_files: dist/AngularAdvisors/index.html
  upload: dist/AngularAdvisors/index.html
  expiration: "1m"
